import Head from 'next/head'
import {BsFillMoonStarsFill} from "react-icons/bs"
import {AiFillTwitterCircle, AiFillLinkedin,AiFillMail} from "react-icons/ai"
import Image from 'next/image';

import { useEffect, useRef } from 'react';
// import Animation from '../../components/animation';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import Guestbook from '../../components/Guestbook';
import About from '../../components/About';
// import Guestbook from '../../components/Guestbook';


export default function Home() {



  

  return (
    <>
      <Head>
        <title>Sakshi Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className='  bg-dark-teal relative h-screen'>
      <ConnectButton/>
     
      
      <body className=' bg-dark-teal z-50'>

     <About/>
     </body>
     </main>
     
    </>
  )
}
